# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=44)),
                ('last_name', models.CharField(max_length=44)),
                ('arrival', models.DateTimeField(auto_now_add=True)),
                ('departure', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Visitors',
                'ordering': ['arrival'],
            },
        ),
    ]
