# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='plate_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
