# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_visitor_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
