# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200109_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
