# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_visitor_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='id',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='plate_number',
            field=models.CharField(default='0000-000', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
